<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ /*
  ~  * Copyright 2026 SawCunha Open System - SawCunhaOS-Organization
  ~  *
  ~  * Licensed under the Apache License, Version 2.0 (the "License");
  ~  * you may not use this file except in compliance with the License.
  ~  * You may obtain a copy of the License at
  ~  *
  ~  *     http://www.apache.org/licenses/LICENSE-2.0
  ~  */
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <modules>
        <module>scos-organization-domain</module>
        <module>scos-organization-api</module>
        <module>scos-organization-application</module>
    </modules>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.2</version>
        <relativePath/>
    </parent>

    <groupId>br.com.sawcunhaos</groupId>
    <artifactId>scos-organization</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <name>SCOS Organization</name>
    <description>Organization and company management system for SCOS, supporting headquarters and branch structures, business users, company configuration, and integration with external identity providers such as Keycloak.</description>
    <url>https://github.com/SawCunhaOS/SawCunhaOS-Organization</url>
    <inceptionYear>2026</inceptionYear>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/SawCunhaOS/SawCunhaOS-Organization</url>
        <connection>scm:git:git://github.com/SawCunhaOS/SawCunhaOS-Organization.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/SawCunhaOS/SawCunhaOS-Organization.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <developers>
        <developer>
            <id>sawcunha</id>
            <name>Sawcunha Community</name>
            <email>community@sawcunha.io</email>
            <url>https://github.com/sawcunha</url>
            <organization>SawCunha Open System</organization>
            <organizationUrl>https://github.com/SawCunhaOS</organizationUrl>
            <roles>
                <role>architect</role>
                <role>maintainer</role>
            </roles>
            <timezone>-3</timezone>
        </developer>
    </developers>

    <organization>
        <name>SawCunha Open System</name>
        <url>https://github.com/SawCunhaOS</url>
    </organization>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/SawCunhaOS/SawCunhaOS-Organization/issues</url>
    </issueManagement>

    <ciManagement>
        <system>GitHub Actions</system>
        <url>https://github.com/SawCunhaOS/SawCunhaOS-Organization/actions</url>
    </ciManagement>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <op_querydsl.version>7.1</op_querydsl.version>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>

        <scos-foundation.version>1.1.0-SNAPSHOT</scos-foundation.version>
        <scos-bom.version>1.0.0</scos-bom.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>br.com.sawcunhaos</groupId>
                <artifactId>scos-bom</artifactId>
                <version>${scos-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>br.com.sawcunhaos</groupId>
                <artifactId>scos-foundation</artifactId>
                <version>${scos-foundation.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>br.com.sawcunhaos</groupId>
                <artifactId>scos-organization-domain</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>br.com.sawcunhaos</groupId>
                <artifactId>scos-organization-application</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.2.5</version>
                </plugin>
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>7.17.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>25</source>
                    <target>25</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <!-- other annotation processors -->
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <snapshotRepository>
            <name>Central Portal Snapshots</name>
            <id>central</id>
            <url>https://central.sonatype.com/repository/maven-snapshots</url>
        </snapshotRepository>
    </distributionManagement>

    <repositories>
        <repository>
            <name>Central Portal Snapshots</name>
            <id>central-portal-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
