openapi: 3.0.3
info:
  title: SawCunhaOS Organization - Department and Position
  description: The SawCunhaOS Organization system contains APIs to use in organization management.
  termsOfService: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Samuel Cunha
    url: https://github.com/SawCunhaOS
    email: samukasaww@live.com
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
servers:
  - url: /organization/api
    description: Generated server url
tags:
  - name: Department
    description: APIs para registro e atualização dos departamentos
  - name: Position
    description: APIs para registro e atualização dos cargos nos departamentos

paths:
  /v1/departments:
    get:
      tags:
        - Department
      summary: Get all departments
      description: Get all departments
      operationId: getAllDepartments
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/paginationFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllDepartmentsResponse'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ GET_DEPARTMENT ]
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
    post:
      tags:
        - Department
      summary: Create a department
      description: Create a department
      operationId: createDepartment
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDepartmentRequest'
        x-jdempotentrequestpayload: true
      responses:
        '201':
          $ref: './ScosComponents.yml#/components/responses/201_CREATED'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ CREATE_DEPARTMENT ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_DEPARTMENT
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
  /v1/departments/{id}:
    get:
      tags:
        - Department
      summary: Get department by id
      description: Get department by id
      operationId: getDepartmentById
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDepartmentResponse'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ GET_DEPARTMENT ]
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
    put:
      tags:
        - Department
      summary: Update department
      description: Update department
      operationId: updateDepartment
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDepartmentRequest'
        x-jdempotentrequestpayload: true
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ UPDATE_DEPARTMENT ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_DEPARTMENT
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
    delete:
      tags:
        - Department
      summary: Delete department
      description: Delete department
      operationId: deleteDepartment
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ DELETE_DEPARTMENT ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_DEPARTMENT
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
  /v1/departments/{id}/enable:
    put:
      tags:
        - Department
      summary: Activate department
      description: Activate department
      operationId: activateDepartment
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ ENABLE_DEPARTMENT ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_DEPARTMENT
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
  /v1/departments/{id}/disable:
    put:
      tags:
        - Department
      summary: Inactivate department
      description: Inactivate department
      operationId: inactivateDepartment
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ DISABLE_DEPARTMENT ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_DEPARTMENT
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_DEPARTMENT ]
  /v1/positions:
    get:
      tags:
        - Position
      summary: Get all positions
      description: Get all positions
      operationId: getAllPositions
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/paginationFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllPositionsResponse'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ GET_POSITION ]
      x-cache: [ SCOS_ORGANIZATION_POSITION ]
    post:
      tags:
        - Position
      summary: Create a position
      description: Create a position
      operationId: createPosition
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePositionRequest'
        x-jdempotentrequestpayload: true
      responses:
        '201':
          $ref: './ScosComponents.yml#/components/responses/201_CREATED'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ CREATE_POSITION ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_POSITION
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_POSITION ]
  /v1/positions/{id}: 
    get:
      tags:
        - Position
      summary: Get position by id
      description: Get position by id
      operationId: getPositionById
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPositionResponse'
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ GET_POSITION ]
      x-cache: [ SCOS_ORGANIZATION_POSITION ]
    put:
      tags:
        - Position
      summary: Update position
      description: Update position
      operationId: updatePosition
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePositionRequest'
        x-jdempotentrequestpayload: true
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ UPDATE_POSITION ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_POSITION
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_POSITION ]
    delete:
      tags:
        - Position
      summary: Delete position
      description: Delete position
      operationId: deletePosition
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ DELETE_POSITION ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_POSITION
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_POSITION ]


  /v1/positions/{id}/enable:
    put:
      tags:
        - Position
      summary: Activate position
      description: Activate position
      operationId: activatePosition
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ ENABLE_POSITION ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_POSITION
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_POSITION ]
  /v1/positions/{id}/disable:
    put:
      tags:
        - Position
      summary: Inactivate position
      description: Inactivate position
      operationId: inactivatePosition
      parameters:
        - $ref: './ScosComponents.yml#/components/parameters/X-Request-ID'
        - $ref: './ScosComponents.yml#/components/parameters/Accept-Language'
        - $ref: './ScosComponents.yml#/components/parameters/idRequest'
      responses:
        '204':
          description: No_Content
        '4XX':
          $ref: './ScosComponents.yml#/components/responses/4XX'
        '5XX':
          $ref: './ScosComponents.yml#/components/responses/5XX'
      x-authorize: [ DISABLE_POSITION ]
      x-jdempotentresource:
        cachePrefix: SCOS_ORGANIZATION_IDP_POSITION
        ttl: 1
      x-cache: [ SCOS_ORGANIZATION_POSITION ]

components:
  schemas:
    Department:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        description:
          type: string
        active:
          type: boolean
    GetDepartmentResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Department'
    GetAllDepartmentsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Department'
        PaginatedDTO:
          $ref: './ScosComponents.yml#/components/schemas/ScosPaginated'
    CreateDepartmentRequest:
      required:
        - code
        - description
      type: object
      properties:
        code:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        description:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
    UpdateDepartmentRequest:
      required:
        - code
        - description
      type: object
      properties:
        code:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        description:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
    
    Position:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        description:
          type: string
        active:
          type: boolean
        department:
          $ref: '#/components/schemas/Department'
    GetPositionResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Position'
    GetAllPositionsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Position'
        PaginatedDTO:
          $ref: './ScosComponents.yml#/components/schemas/ScosPaginated'
    CreatePositionRequest:
      required:
        - code
        - description
        - departmentId
      type: object
      properties:
        code:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        description:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        departmentId:
          type: integer
          format: int64
          x-required-message: SCOS-003
    UpdatePositionRequest:
      required:
        - code
        - description
        - departmentId
      type: object
      properties:
        code:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        description:
          type: string
          x-required-message: SCOS-003
          x-empty-message: SCOS-001
        departmentId:
          type: integer
          format: int64
          x-required-message: SCOS-003