syntax = "proto3";

option java_multiple_files = true;
option java_package = "br.com.sawcunhaos.organization.grpc.proto";
option java_outer_classname = "RegistryProto";

package br.com.sawcunhaos.organization.grpc.proto;

service RegistryService {
  rpc registrySystem(RegistrySystemRequest) returns (RegistrySystemResponse);
  rpc registryResources(RegistryResourcesRequest) returns (Empty);
}

message RegistrySystemRequest {
  string name = 1;
  string code = 2;
  string description = 3;
  string version = 4;
}

message RegistrySystemResponse {
  string system_id = 1;
  string secret_key = 2;
  bool update = 3;
}

message Resource {
  string code = 1;
  string description_pt = 2;
  string description_en = 3;
  bool active = 4;
}

message RegistryResourcesRequest {
  string system_id = 1;
  repeated Resource resources = 2;
}

message Empty {

}
