
#
# /*
#  * Copyright 2026 SawCunha Open System - SawCunhaOS-Organization
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  */
#

EMPLOYEE_MIN_AGE=Define a idade miminima para um funcionario
COMPANY_HIERARCHY_MAX_DEPTH=Define a profundidade maxima da hierarquia da empresa
LOGIN_INACTIVITY_TIMEOUT_DAYS=Define o tempo de inatividade do login para desativação
EMPLOYEE_EMAIL_DOMAIN=Define o dominio do email da empresa
DEFAULT_COMPANY_ID=Define a empresa padrao
