<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>br.com.sawcunhaos.flow</groupId>
        <artifactId>organization</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>flow-organization-usecase</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>br.com.sawcunhaos.flow</groupId>
            <artifactId>flow-organization-domain</artifactId>
        </dependency>

        <dependency>
            <groupId>br.com.sawcunhaos</groupId>
            <artifactId>scos-foundation-exception</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.sawcunhaos</groupId>
            <artifactId>scos-foundation-utils</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    <templateResourcePath>classpath:/templates</templateResourcePath>
                </configuration>
                <executions>
                    <execution>
                        <id>ScosOrganization_Company</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Company.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Catalog</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Catalog.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Department-Position</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Department-Position.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Configuration</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Configuration.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Outbox</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Outbox.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Reason</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Reason.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Employee</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Employee.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ScosOrganization_Login</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/../etc/api/organization/ScosOrganization_Login.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>br.com.sawcunhaos.organization.api.controller</apiPackage>
                            <modelPackage>br.com.sawcunhaos.organization.api.dto</modelPackage>
                            <templateResourcePath>mustaches</templateResourcePath>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApis>false</generateApis>
                            <generateModels>true</generateModels>
                            <skipValidateSpec>true</skipValidateSpec>
                            <typeMappings>
                                <typeMapping>time=LocalTime</typeMapping>
                                <typeMapping>Double=BigDecimal</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>LocalTime=java.time.LocalTime</importMapping>
                                <typeMapping>BigDecimal=java.math.BigDecimal</typeMapping>
                            </importMappings>
                            <configOptions>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>false</useSpringController>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>br.com.sawcunhaos</groupId>
                        <artifactId>scos-foundation-utils</artifactId>
                        <version>${scos-foundation.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>
